raise Exception('some error occurred')
